#服务端口
server:
  port: 18081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.14.196.116:8848 #nacos注册中心地址
    sentinel:
      transport:
        dashboard: 106.14.196.116:8080  #sentinel面板端口
        port: 8719                 #sentinel通信端口
  datasource:   #数据源配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.196.116:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:  #redis配置
    host: 106.14.196.116
  zipkin: #zipkin
    base-url: http://106.14.196.116:9411  #服务地址
    discovery-client-enabled: false  #追踪ziplkin自己的请求，选择否
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1  #采集频率 0~1，1代表100%
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml  # mapper.xml路径
  type-aliases-package: com.atguigu.gmall.pms.entity #实体类包
  global-config:    #mybatis全局配置
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true  #开启sentinel流控，默认使用hystrix